apiVersion: v1
kind: Service
metadata:
  name: eks-deployment-udacity-capstone
  namespace: eks-deployment-udacity-capstone
  labels:
    app: eks-deployment-udacity-capstone
spec:
  selector:
    app: eks-deployment-udacity-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80