apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deployment-udacity-capstone
  namespace: eks-deployment-udacity-capstone
  labels:
    app: eks-deployment-udacity-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-deployment-udacity-capstone
  template:
    metadata:
      labels:
        app: eks-deployment-udacity-capstone
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: thanhtung249/udacity_capstones
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux